import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1771679344874 implements MigrationInterface {
    name = 'InitialSchema1771679344874'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Production DB already has this schema from synchronize:true — skip if tables exist
        const alreadyExists = await queryRunner.hasTable('specialty');
        if (alreadyExists) return;

        await queryRunner.query(`CREATE TABLE "specialty" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_6caedcf8a5f84e3072c5a380a16" UNIQUE ("name"), CONSTRAINT "PK_9cf4ae334dc4a1ab1e08956460e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "label" character varying NOT NULL, "sort_order" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e77743a7955e652aa7ebf4a7650" UNIQUE ("code"), CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "resource" character varying NOT NULL, "action" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_b7f40c3248fc7ad7c35151e2d11" UNIQUE ("resource", "action"), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "street" character varying NOT NULL, "number" character varying NOT NULL, "complement" character varying, "neighborhood" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying(2) NOT NULL, "zip_code" character varying NOT NULL, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "person_identification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "cpf" character varying NOT NULL, "rg" character varying, "sus_card_number" character varying, "date_of_birth" date NOT NULL, "issuing_authority" character varying, "person_id" uuid, CONSTRAINT "UQ_05d9d30f7578b408bff1499a2f5" UNIQUE ("cpf"), CONSTRAINT "UQ_87cf43a4ab0aa6f7709f303fe1e" UNIQUE ("sus_card_number"), CONSTRAINT "REL_384a30e191f7a5ca82a10892a2" UNIQUE ("person_id"), CONSTRAINT "PK_28656546e0a2238a0be89c8f402" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "value" character varying NOT NULL, "label" character varying, "is_primary" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "person" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "gender" character varying NOT NULL, "address_id" uuid, CONSTRAINT "PK_5fdaf670315c4b7e70cce85daa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "crm" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "person_id" uuid, CONSTRAINT "UQ_aab8f24bc311f018cf511577ac6" UNIQUE ("crm"), CONSTRAINT "REL_fb38f3d7d38878d734a3fbb562" UNIQUE ("person_id"), CONSTRAINT "PK_ee6bf6c8de78803212c548fcb94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "cnpj" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "address_id" uuid, CONSTRAINT "UQ_480aaa8101e24b3d4e4d874e441" UNIQUE ("cnpj"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospital" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "cnes_code" character varying NOT NULL, "organization_id" uuid, CONSTRAINT "UQ_f6403d3a720e755cd4e4e0977ab" UNIQUE ("cnes_code"), CONSTRAINT "REL_f67c3723a2a29ce955c0822568" UNIQUE ("organization_id"), CONSTRAINT "PK_10f19e0bf17ded693ea0da07d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "municipality" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "ibge_code" character varying NOT NULL, "state" character varying(2) NOT NULL, "organization_id" uuid, CONSTRAINT "UQ_1828580a0f657cd921e5601f0a1" UNIQUE ("ibge_code"), CONSTRAINT "REL_1de54193a06db1f77d9c1388c6" UNIQUE ("organization_id"), CONSTRAINT "PK_281ad341f20df7c41b83a182e2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hotel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "municipality_id" uuid, CONSTRAINT "REL_c661bfffed1d0653bfa5ac5c2a" UNIQUE ("organization_id"), CONSTRAINT "PK_3a62ac86b369b36c1a297e9ab26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "principal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "password_hash" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP, "person_id" uuid, "organization_id" uuid, CONSTRAINT "UQ_bba9a1cd8e7a25d485624988732" UNIQUE ("username"), CONSTRAINT "REL_183b62a87d05993da02c033776" UNIQUE ("person_id"), CONSTRAINT "REL_e854ba038b5e54191b5493c926" UNIQUE ("organization_id"), CONSTRAINT "PK_b3ff9fc87cb26d8e16f1cc56745" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tfd_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "protocol_number" character varying NOT NULL, "diagnosis_cid" character varying NOT NULL, "procedure_description" text NOT NULL, "justification" text NOT NULL, "request_date" date NOT NULL, "travel_date" date, "return_date" date, "transport_type" character varying NOT NULL, "estimated_cost" numeric(10,2), "notes" text, "patient_person_id" uuid, "companion_person_id" uuid, "requesting_doctor_id" uuid, "destination_hospital_id" uuid, "hotel_id" uuid, "municipality_id" uuid, "created_by_principal_id" uuid, "status_id" uuid, CONSTRAINT "UQ_c1973a92ee5bc0e5f0e40489adb" UNIQUE ("protocol_number"), CONSTRAINT "PK_1f0a2c2aca4b8b535a9dd90c525" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "module_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "sort_order" integer NOT NULL, "module_id" uuid, "status_id" uuid, CONSTRAINT "PK_7f1a12025935c3785f9c15cae78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "module" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_1ccb6257978189bc9d5e0bedf76" UNIQUE ("code"), CONSTRAINT "PK_0e20d657f968b051e674fbe3117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "person_contact" ("person_id" uuid NOT NULL, "contact_id" uuid NOT NULL, CONSTRAINT "PK_2f6f367b5d2e144ad4f3b7ff365" PRIMARY KEY ("person_id", "contact_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed78b7b2d50539bbc6796c70b4" ON "person_contact" ("person_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a3b1dc394a89919b660c259c0" ON "person_contact" ("contact_id") `);
        await queryRunner.query(`CREATE TABLE "doctor_specialty" ("doctor_id" uuid NOT NULL, "specialty_id" uuid NOT NULL, CONSTRAINT "PK_32a95d0b8737e4b4943b75b7b1c" PRIMARY KEY ("doctor_id", "specialty_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f094b41552f4096abd621b7289" ON "doctor_specialty" ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7792fabe9bfec740f0ec902734" ON "doctor_specialty" ("specialty_id") `);
        await queryRunner.query(`CREATE TABLE "organization_contact" ("organization_id" uuid NOT NULL, "contact_id" uuid NOT NULL, CONSTRAINT "PK_016d831bc6b6d2a7cdee99e0717" PRIMARY KEY ("organization_id", "contact_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e0d0ad3a5fef43361d5d5bf2b3" ON "organization_contact" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb6fa7d4e5e16d63eac18072c5" ON "organization_contact" ("contact_id") `);
        await queryRunner.query(`CREATE TABLE "hospital_specialty" ("hospital_id" uuid NOT NULL, "specialty_id" uuid NOT NULL, CONSTRAINT "PK_a9beab073416e33c949ee7aeb18" PRIMARY KEY ("hospital_id", "specialty_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99d780b89eb17d094850f86f47" ON "hospital_specialty" ("hospital_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef95b08b18bf396e693002eb18" ON "hospital_specialty" ("specialty_id") `);
        await queryRunner.query(`CREATE TABLE "principal_role" ("principal_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_568d1fb9df90f4195f93c498b42" PRIMARY KEY ("principal_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_871c384be56e8cf8748a2caff9" ON "principal_role" ("principal_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18880aeeaef9b8f31713af2a1a" ON "principal_role" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "principal_organization" ("principal_id" uuid NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "PK_15dac6dd9c5098caaf6d9219d6a" PRIMARY KEY ("principal_id", "organization_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2fa3df63cad16f264a3c1c176" ON "principal_organization" ("principal_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d112d91840c183ad63d15ee39" ON "principal_organization" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "person_identification" ADD CONSTRAINT "FK_384a30e191f7a5ca82a10892a2a" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person" ADD CONSTRAINT "FK_cd587348ca3fec07931de208299" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor" ADD CONSTRAINT "FK_fb38f3d7d38878d734a3fbb562b" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_0f31fe3925535afb5462326d7d6" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital" ADD CONSTRAINT "FK_f67c3723a2a29ce955c08225682" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "municipality" ADD CONSTRAINT "FK_1de54193a06db1f77d9c1388c64" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel" ADD CONSTRAINT "FK_c661bfffed1d0653bfa5ac5c2a7" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel" ADD CONSTRAINT "FK_7dde97fd503a2ce092d324d8d0e" FOREIGN KEY ("municipality_id") REFERENCES "municipality"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "principal" ADD CONSTRAINT "FK_183b62a87d05993da02c0337769" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "principal" ADD CONSTRAINT "FK_e854ba038b5e54191b5493c9268" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_85c8b5d88ea017b400c6c180bc1" FOREIGN KEY ("patient_person_id") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_6528023e1c4db1666e062470c1a" FOREIGN KEY ("companion_person_id") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_8f228336537a05a019a84f77abd" FOREIGN KEY ("requesting_doctor_id") REFERENCES "doctor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_35ceb8f90e1e7fc0aa360441d00" FOREIGN KEY ("destination_hospital_id") REFERENCES "hospital"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_9c6a2734ffad47d66340ebbb76f" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_706d250309f41263c63e5cdff2d" FOREIGN KEY ("municipality_id") REFERENCES "municipality"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_fefe1fb162cf16c19ecd29d9f9f" FOREIGN KEY ("created_by_principal_id") REFERENCES "principal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tfd_request" ADD CONSTRAINT "FK_f8c65605fc129b877ad69273539" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_status" ADD CONSTRAINT "FK_23b217c8ad00d8f53b8ace21125" FOREIGN KEY ("module_id") REFERENCES "module"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_status" ADD CONSTRAINT "FK_99ddc69d8d5828ba665deece664" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_contact" ADD CONSTRAINT "FK_ed78b7b2d50539bbc6796c70b4e" FOREIGN KEY ("person_id") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_contact" ADD CONSTRAINT "FK_7a3b1dc394a89919b660c259c08" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "doctor_specialty" ADD CONSTRAINT "FK_f094b41552f4096abd621b72896" FOREIGN KEY ("doctor_id") REFERENCES "doctor"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "doctor_specialty" ADD CONSTRAINT "FK_7792fabe9bfec740f0ec9027347" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "organization_contact" ADD CONSTRAINT "FK_e0d0ad3a5fef43361d5d5bf2b39" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "organization_contact" ADD CONSTRAINT "FK_eb6fa7d4e5e16d63eac18072c53" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "hospital_specialty" ADD CONSTRAINT "FK_99d780b89eb17d094850f86f478" FOREIGN KEY ("hospital_id") REFERENCES "hospital"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "hospital_specialty" ADD CONSTRAINT "FK_ef95b08b18bf396e693002eb188" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "principal_role" ADD CONSTRAINT "FK_871c384be56e8cf8748a2caff91" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "principal_role" ADD CONSTRAINT "FK_18880aeeaef9b8f31713af2a1a0" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "principal_organization" ADD CONSTRAINT "FK_f2fa3df63cad16f264a3c1c1767" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "principal_organization" ADD CONSTRAINT "FK_2d112d91840c183ad63d15ee394" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "principal_organization" DROP CONSTRAINT "FK_2d112d91840c183ad63d15ee394"`);
        await queryRunner.query(`ALTER TABLE "principal_organization" DROP CONSTRAINT "FK_f2fa3df63cad16f264a3c1c1767"`);
        await queryRunner.query(`ALTER TABLE "principal_role" DROP CONSTRAINT "FK_18880aeeaef9b8f31713af2a1a0"`);
        await queryRunner.query(`ALTER TABLE "principal_role" DROP CONSTRAINT "FK_871c384be56e8cf8748a2caff91"`);
        await queryRunner.query(`ALTER TABLE "hospital_specialty" DROP CONSTRAINT "FK_ef95b08b18bf396e693002eb188"`);
        await queryRunner.query(`ALTER TABLE "hospital_specialty" DROP CONSTRAINT "FK_99d780b89eb17d094850f86f478"`);
        await queryRunner.query(`ALTER TABLE "organization_contact" DROP CONSTRAINT "FK_eb6fa7d4e5e16d63eac18072c53"`);
        await queryRunner.query(`ALTER TABLE "organization_contact" DROP CONSTRAINT "FK_e0d0ad3a5fef43361d5d5bf2b39"`);
        await queryRunner.query(`ALTER TABLE "doctor_specialty" DROP CONSTRAINT "FK_7792fabe9bfec740f0ec9027347"`);
        await queryRunner.query(`ALTER TABLE "doctor_specialty" DROP CONSTRAINT "FK_f094b41552f4096abd621b72896"`);
        await queryRunner.query(`ALTER TABLE "person_contact" DROP CONSTRAINT "FK_7a3b1dc394a89919b660c259c08"`);
        await queryRunner.query(`ALTER TABLE "person_contact" DROP CONSTRAINT "FK_ed78b7b2d50539bbc6796c70b4e"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "module_status" DROP CONSTRAINT "FK_99ddc69d8d5828ba665deece664"`);
        await queryRunner.query(`ALTER TABLE "module_status" DROP CONSTRAINT "FK_23b217c8ad00d8f53b8ace21125"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_f8c65605fc129b877ad69273539"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_fefe1fb162cf16c19ecd29d9f9f"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_706d250309f41263c63e5cdff2d"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_9c6a2734ffad47d66340ebbb76f"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_35ceb8f90e1e7fc0aa360441d00"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_8f228336537a05a019a84f77abd"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_6528023e1c4db1666e062470c1a"`);
        await queryRunner.query(`ALTER TABLE "tfd_request" DROP CONSTRAINT "FK_85c8b5d88ea017b400c6c180bc1"`);
        await queryRunner.query(`ALTER TABLE "principal" DROP CONSTRAINT "FK_e854ba038b5e54191b5493c9268"`);
        await queryRunner.query(`ALTER TABLE "principal" DROP CONSTRAINT "FK_183b62a87d05993da02c0337769"`);
        await queryRunner.query(`ALTER TABLE "hotel" DROP CONSTRAINT "FK_7dde97fd503a2ce092d324d8d0e"`);
        await queryRunner.query(`ALTER TABLE "hotel" DROP CONSTRAINT "FK_c661bfffed1d0653bfa5ac5c2a7"`);
        await queryRunner.query(`ALTER TABLE "municipality" DROP CONSTRAINT "FK_1de54193a06db1f77d9c1388c64"`);
        await queryRunner.query(`ALTER TABLE "hospital" DROP CONSTRAINT "FK_f67c3723a2a29ce955c08225682"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_0f31fe3925535afb5462326d7d6"`);
        await queryRunner.query(`ALTER TABLE "doctor" DROP CONSTRAINT "FK_fb38f3d7d38878d734a3fbb562b"`);
        await queryRunner.query(`ALTER TABLE "person" DROP CONSTRAINT "FK_cd587348ca3fec07931de208299"`);
        await queryRunner.query(`ALTER TABLE "person_identification" DROP CONSTRAINT "FK_384a30e191f7a5ca82a10892a2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d112d91840c183ad63d15ee39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2fa3df63cad16f264a3c1c176"`);
        await queryRunner.query(`DROP TABLE "principal_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18880aeeaef9b8f31713af2a1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_871c384be56e8cf8748a2caff9"`);
        await queryRunner.query(`DROP TABLE "principal_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef95b08b18bf396e693002eb18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99d780b89eb17d094850f86f47"`);
        await queryRunner.query(`DROP TABLE "hospital_specialty"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb6fa7d4e5e16d63eac18072c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0d0ad3a5fef43361d5d5bf2b3"`);
        await queryRunner.query(`DROP TABLE "organization_contact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7792fabe9bfec740f0ec902734"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f094b41552f4096abd621b7289"`);
        await queryRunner.query(`DROP TABLE "doctor_specialty"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a3b1dc394a89919b660c259c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed78b7b2d50539bbc6796c70b4"`);
        await queryRunner.query(`DROP TABLE "person_contact"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "module"`);
        await queryRunner.query(`DROP TABLE "module_status"`);
        await queryRunner.query(`DROP TABLE "tfd_request"`);
        await queryRunner.query(`DROP TABLE "principal"`);
        await queryRunner.query(`DROP TABLE "hotel"`);
        await queryRunner.query(`DROP TABLE "municipality"`);
        await queryRunner.query(`DROP TABLE "hospital"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "doctor"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP TABLE "person_identification"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "specialty"`);
    }

}
